name: 機能リクエスト
description: このプロジェクトにアイデアを提案する。
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: 重複するIssueが既に存在していませんか？
      description: あなたが作成しようとしているIssueが、既に存在するかどうか確認してください。
      options:
        - label: 重複するIssueがないか確認しました。
          required: true
  - type: textarea
    attributes:
      label: 説明
      description: 機能リクエストの内容を簡潔に説明してください。既存の問題点を解決するための機能リクエストの場合は、その問題点もわかりやすく簡潔に説明してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 解決策の提案
      description: 機能リクエストを実現するための解決策をわかりやすく簡潔に説明してください。
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: その他
      description: このIssueに関するその他の情報やスクリーンショットをここに追加してください。
    validations:
      required: false
