// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfLPgZOhj2klS9u2XaYt6aDWvHcNMM3I',
    appId: '1:632527740899:web:049f0f00cc7552473b8ad6',
    messagingSenderId: '632527740899',
    projectId: 'quiz-shower',
    authDomain: 'quiz-shower.firebaseapp.com',
    storageBucket: 'quiz-shower.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGggLdSL7l7yxI67BMqKot7StjJ0fbdtM',
    appId: '1:632527740899:android:4633caf55b93d06b3b8ad6',
    messagingSenderId: '632527740899',
    projectId: 'quiz-shower',
    storageBucket: 'quiz-shower.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2Ublv8NxAHPtLwb4uPCJAUKDq-cWveQ',
    appId: '1:632527740899:ios:630109c14b5bfa6e3b8ad6',
    messagingSenderId: '632527740899',
    projectId: 'quiz-shower',
    storageBucket: 'quiz-shower.appspot.com',
    iosBundleId: 'app.web.quizShower',
  );
}
