name: Functions

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  functions:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "functions/pnpm-lock.yaml"

      - name: Install dependencies
        run: |
          cd functions
          pnpm install

      - name: Format
        run: |
          cd functions
          pnpm run format:check

      - name: Lint
        run: |
          cd functions
          pnpm run lint

      - name: Build
        run: |
          cd functions
          pnpm run build
