name: Label approved pull requests

on: pull_request_review

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
          REMOVE_LABEL: "awaiting%20review"
